hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: output_ldc2d_importance_sampling/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working direcotry unchaned
    config:
      override_dirname:
        exclude_keys:
          - TRAIN.checkpoint_path
          - TRAIN.pretrained_model_path
          - EVAL.pretrained_model_path
          - mode
          - output_dir
          - log_freq
  callbacks:
    init_callback:
      _target_: ppsci.utils.callbacks.InitCallback
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: train # running mode: train/eval
seed: 2023
output_dir: ${hydra:run.dir}
log_freq: 20

# set working condition
NU: 0.01
RHO: 1.0

# model settings
MODEL:
  input_keys: ["x", "y"]
  output_keys: ["u", "v", "p"]
  num_layers: 6
  hidden_size: 512
  activation: "silu"
  weight_norm: true

# training settings
TRAIN:
  epochs: 10
  iters_per_epoch: 1000
  save_freq: 0
  eval_during_train: true
  eval_freq: 1
  lr_scheduler:
    epochs: ${TRAIN.epochs}
    iters_per_epoch: ${TRAIN.iters_per_epoch}
    learning_rate: 0.001
    gamma: 0.95
    decay_steps: 4000
    by_epoch: false
  batch_size:
    bc_top: 1000
    bc_noslip: 1000
    pde: 4000
  pretrained_model_path: null
  checkpoint_path: null

# evaluation settings
EVAL:
  pretrained_model_path: null
  eval_with_no_grad: true
  batch_size: 1024
