{
    "Fluid properties":
    {
        "Reynold's number":3900,
    },
    
    "hyper parameters":
    {
        "number of epoch":40000,

        "random seed":42,

        "learning rate":0.001,

        "hidden size":512,

        "batch size":
        {
            
            "interior":4000,    # 160000 points

            "inlet":1162,   # 4648 points
            "outlet":358,   # 4648 points
            "cylinder":358, # 1432 points
            "top":320, # 10016 points
            "bottom":9944, # 1432 points

            "initial condition":6400,  # 131520 points
            "supervised":6400,  # 131520 points
        },

        "weight of losses":
        {
            "pde":1.0,
            "initial condition":5.0,

            "front":2.0,
            "back":2.0,
            "left inlet":2.0,
            "right outlet":1.0,
            "top":2.0,
            "bottom":2.0,
            "cylinder":5.0,
            
            "supervised":10.0,
        },

        "Simulated Annealing":
        {
            "warm epochs":5000,
        },
    }

}

